package mapping;
// Generated Jul 18, 2023 10:03:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int id;
     private String name;
     private Set researches = new HashSet(0);

    public Area() {
    }

	
    public Area(int id) {
        this.id = id;
    }
    public Area(int id, String name, Set researches) {
       this.id = id;
       this.name = name;
       this.researches = researches;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getResearches() {
        return this.researches;
    }
    
    public void setResearches(Set researches) {
        this.researches = researches;
    }




}


