package mapping;
// Generated Jul 18, 2023 10:03:05 AM by Hibernate Tools 4.3.1



/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private String nic;
     private String fname;
     private String lname;
     private String institution;
     private String type;

    public Author() {
    }

	
    public Author(String nic) {
        this.nic = nic;
    }
    public Author(String nic, String fname, String lname, String institution, String type) {
       this.nic = nic;
       this.fname = fname;
       this.lname = lname;
       this.institution = institution;
       this.type = type;
    }
   
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


