package mapping;
// Generated Jul 18, 2023 10:03:05 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private Country country;
     private String fname;
     private String lname;
     private String nic;
     private String email;
     private String mobile;
     private String password;

    public User() {
    }

	
    public User(int id, Country country) {
        this.id = id;
        this.country = country;
    }
    public User(int id, Country country, String fname, String lname, String nic, String email, String mobile, String password) {
       this.id = id;
       this.country = country;
       this.fname = fname;
       this.lname = lname;
       this.nic = nic;
       this.email = email;
       this.mobile = mobile;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


